let restaurantList = [
  {
    id: 1,
    name: "The Spice Route",
    cuisines: ["North Indian", "Chinese", "Thai"],
    rating: 4.5,
    eta: "30 mins",
    cost_for_two: 700,
    image_url: "https://source.unsplash.com/random/508x320?food&sig=1",
  },
  {
    id: 2,
    name: "Pizza Paradise",
    cuisines: ["Italian", "Fast Food"],
    rating: 4.2,
    eta: "25 mins",
    cost_for_two: 500,
    image_url: "https://source.unsplash.com/random/508x320?food&sig=2",
  },
  {
    id: 3,
    name: "Burger Hub",
    cuisines: ["American", "Fast Food"],
    rating: 4.0,
    eta: "20 mins",
    cost_for_two: 450,
    image_url: "https://source.unsplash.com/random/508x320?food&sig=3",
  },
  {
    id: 4,
    name: "Sushi World",
    cuisines: ["Japanese"],
    rating: 4.8,
    eta: "35 mins",
    cost_for_two: 1200,
    image_url: "https://source.unsplash.com/random/508x320?food&sig=4",
  },
  {
    id: 5,
    name: "Taco Town",
    cuisines: ["Mexican"],
    rating: 4.3,
    eta: "30 mins",
    cost_for_two: 600,
    image_url: "https://source.unsplash.com/random/508x320?food&sig=5",
  },
  {
    id: 6,
    name: "Curry Corner",
    cuisines: ["Indian", "South Indian"],
    rating: 4.4,
    eta: "28 mins",
    cost_for_two: 550,
    image_url: "https://source.unsplash.com/random/508x320?food&sig=6",
  },
  {
    id: 7,
    name: "Pasta Point",
    cuisines: ["Italian"],
    rating: 4.1,
    eta: "27 mins",
    cost_for_two: 650,
    image_url: "https://source.unsplash.com/random/508x320?food&sig=7",
  },
  {
    id: 8,
    name: "Salad Station",
    cuisines: ["Healthy", "Salads"],
    rating: 4.6,
    eta: "22 mins",
    cost_for_two: 400,
    image_url: "https://source.unsplash.com/random/508x320?food&sig=8",
  },
  {
    id: 9,
    name: "Grill Master",
    cuisines: ["Barbecue", "American"],
    rating: 4.3,
    eta: "32 mins",
    cost_for_two: 750,
    image_url: "https://source.unsplash.com/random/508x320?food&sig=9",
  },
  {
    id: 10,
    name: "Noodle Nirvana",
    cuisines: ["Chinese", "Thai"],
    rating: 4.7,
    eta: "29 mins",
    cost_for_two: 550,
    image_url: "https://source.unsplash.com/random/508x320?food&sig=10",
  },
  {
    id: 11,
    name: "Dessert Delights",
    cuisines: ["Desserts", "Bakery"],
    rating: 4.9,
    eta: "15 mins",
    cost_for_two: 300,
    image_url: "https://source.unsplash.com/random/508x320?food&sig=11",
  },
  {
    id: 12,
    name: "Seafood Shack",
    cuisines: ["Seafood", "Grill"],
    rating: 4.2,
    eta: "33 mins",
    cost_for_two: 900,
    image_url: "https://source.unsplash.com/random/508x320?food&sig=12",
  },
  {
    id: 13,
    name: "Vegan Vibes",
    cuisines: ["Vegan", "Healthy"],
    rating: 4.5,
    eta: "24 mins",
    cost_for_two: 500,
    image_url: "https://source.unsplash.com/random/508x320?food&sig=13",
  },
  {
    id: 14,
    name: "Bistro Bliss",
    cuisines: ["Continental", "Cafe"],
    rating: 4.4,
    eta: "26 mins",
    cost_for_two: 700,
    image_url: "https://source.unsplash.com/random/508x320?food&sig=14",
  },
  {
    id: 15,
    name: "Dosa Delight",
    cuisines: ["South Indian", "Fast Food"],
    rating: 4.3,
    eta: "23 mins",
    cost_for_two: 450,
    image_url: "https://source.unsplash.com/random/508x320?food&sig=15",
  },
];

export { restaurantList };
